### ISSUE TITLE
[object Event] alert

### ISSUE THREAD

**Issue by JellevdHeuvel** [gildas-lormeau/zip.js#138]
every time i try to upload a zip I get the alert:

[object Event]

what am I doing wrong? I have the same setup found on

http://gildas-lormeau.github.io/zip.js/demos/demo2.html

**Comment by Rob--W** [comment]
The `alert` is shown when an error occurs. Could you change `alert` to `console.log` and tell me what's printed?

**Comment by Udofalcon** [comment]
Hey @Rob--W 

I was having a similar issue that @JellevdHeuvel has with the demo2 setup where I was getting the [object Event] alert. The error in the console pointed towards a worker and once I updated the zip.workerScriptsPath variable to the proper location for my setup, the alert no longer triggered and things seem to be peachy now.

**Comment by RNabel** [comment]
Hey @Rob--W, just wanted to confirm that I experienced the same problem and @Udofalcon's fix worked. All javascript files were included correctly, so why did it fall back to the default paths?

**Comment by Rob--W** [comment]
@RNabel Can you share a link to your setup for debugging purposes?

**Comment by SatanWoo** [comment]
Can someone show how to fix this issue. I have add zip.workerScriptsPath = 'filePath' in demo2.js. But it still doesn't work

**Comment by RNabel** [comment]
The workaround that worked for me was changing [this array](https://github.com/gildas-lormeau/zip.js/blob/1bead0a3bb9d2e50ea34094bbfe9bb6a2196939a/WebContent/zip.js#L872) to contain the actual paths to the respective files.

**Comment by Udofalcon** [comment]
@SatanWoo In my root directory I have my index.html and a "js" folder, where in my js folder I have the zip.js files and my own script. I have this near the top of the script:
`zip.workerScriptsPath = "js/";`

When I updated that variable, the error no longer triggered and the script worked fine.

**Comment by SatanWoo** [comment]
@Udofalcon Thanks! That works fine for me

**Comment by SatanWoo** [comment]
@Udofalcon I just made a mistake by just typing "/lib". Instead, we need to type "/lib/"

**Comment by dolare1** [comment]
I am also getting [object Event] alert. I tried all the aforementioned fixes including the paths (absolute and relative) of workerScripts variable. 

`var worker = new Worker(scripts[0]);
 console.log("worker initialized with " + scripts[0]);
 // record total consumed time by inflater/deflater/crc32 in this worker
 worker.codecTime = worker.crcTime = 0;
 console.log("after codectime");
 worker.postMessage({ type: 'importScripts', scripts: scripts.slice(1) });
 console.log("after postmessage with " + scripts.slice(1))`

All the three console.log statements are printed in the browser successfully which makes me wonder if the problem is not related to whether scripts have loaded properly or not. I do not get an error that says worker object is undefined. What else could be going wrong?

I am testing on IE 10 with "useWebWorkers" turned on. Any pointers?

Thank you!

**Comment by luochang212** [comment]
@Udofalcon Thanks a lot, that works for me too!
