### ISSUE TITLE
z-worker.js loaded multiple times

### ISSUE THREAD

**Issue by kofifus** [gildas-lormeau/zip.js#139]
Looking at the network tab in chrome developer tools I can see that z-worker.js is loaded on every zip creation.

Is this normal behavior ?  
Thx!

**Comment by Rob--W** [comment]
It seems normal. If you create a new ZipWriter, a new Worker is created: https://github.com/gildas-lormeau/zip.js/blob/1bead0a3bb9d2e50ea34094bbfe9bb6a2196939a/WebContent/zip.js#L849-L862

Are you experiencing any issues with the worker script?

**Comment by kofifus** [comment]
If I do a lot of creating new ZipWriters, is the an issue with the browser loading the file many times ? does it mean memory is taken multiple times to hold z-worker.js code ? in general I believe it's better a js file is loaded only once

**Comment by Rob--W** [comment]
With the proper headers, the worker script ought to be cached, so the impact should be negligible.

Technically, it is possible to create a worker from a string and ensure that the worker is cached (as I mentioned in https://github.com/gildas-lormeau/zip.js/pull/113#issuecomment-64918392). Patches are welcome.

**Comment by kofifus** [comment]
isn't it possible to simply check if z-worker.js has already been loaded (ie some var is defined) and not load it again ?

**Comment by Rob--W** [comment]
`z-worker.js` is loaded in a Web Worker. Think of a Web Worker as a new frame, the browser needs to retrieve the script before it can run the code.

**Comment by kofifus** [comment]
ok got it thx

**Comment by thw0rted** [comment]
@Rob--W sorry for the thread necro but I'm seeing something related and wasn't sure if it warrants an issue of its own.  If I read this correctly, creating a whole new new ZIP file should cause the browser to load the corresponding script(s).  Is that also supposed to happen for each file added?

I'm seeing `deflate.js` loaded once per file, but it's not happening in this [example Plunkr](https://plnkr.co/edit/g1hKRu?p=info) I put together, only in [the actual consuming project](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Export%20KML.html) that I'm troubleshooting.  Run the Plunkr example and it only loads `deflate` once to add 100 files, but click the Download button in the Cesium example and it loads `deflate` 5 times to add 5 files to the ZIP (KMZ) that it creates.

I'm aware the browser only actually makes one network request even in the latter case, because the server is correctly configured, but I'm trying to figure out why I don't see a similar number of cache responses in my Plunkr example, so that it will behave well even if the server has bad caching policies.

**Comment by Rob--W** [comment]
@thw0rted That Cesium project of yours uses an old version of zip.js. Older versions created a new worker for every deflate task, but in #108 the implementation was changed to pool workers where possible. Upgrade zip.js if you want fewer creation worker requests.

**Comment by thw0rted** [comment]
Oh, thank you! The Cesium team distributes some of their dependencies along with their own code -- they don't use npm/webpack for builds, I think -- so I couldn't tell what version of Zip it was just from the header comments, etc., but it looked "about right".  I will file an issue with Cesium.
