### ISSUE TITLE
zip.js using web workers failing after grunt build due to zip.workerScriptsPath

### ISSUE THREAD

**Issue by a2ankitrai** [gildas-lormeau/zip.js#156]
zip.js using web workers works fine when running the application directly. To achieve this we need to set the workerScriptsPath by following: 
`zip.workerScriptsPath = '<zip_js_dir>/';`

 But after the grunt build process all of the application js files gets minified and bundled together. So this setting up of workerScriptsPath no longer makes any sense and zip.js fails.

I have tried setting the workerScriptsPath variable to current directory by following :- 
`zip.workerScriptsPath="."`
This does not worked out
I have also tried not setting the workerScriptsPath variable so that it might take directly from the directory of the page's base URL but this also does not work.

Is there any way to use zip.js using web workers after the grunt build process.

**Comment by duanyao** [comment]
There is a section in the doc on concatenating scripts:
https://gildas-lormeau.github.io/zip.js/core-api.html#concat-scripts

Normally you can't bundle `zip.js` and worker scripts (`z-worker.js` etc.) together because they are supposed to run in different threads. If you really want to, you can try to load worker scripts via blob-url.
