### ISSUE TITLE
Zip64 (4gb+ file size)

### ISSUE THREAD

**Issue by softwaltz** [gildas-lormeau/zip.js#180]
Is there any way to solve this problem??

**Comment by jimmywarting** [comment]
Also curious

**Comment by mahmed0715** [comment]
+1

**Comment by mahmed0715** [comment]
and why is this limit? anyone knows about the reason? and how to solve it? TIA

**Comment by Rob--W** [comment]
The original zip file format only supported 32-bit unsigned integers to denote file size, so the maximum size of a file is 2^32 = 4GB. To support over 4 GB, the library needs to support the [zip64 format](https://en.wikipedia.org/wiki/Zip_(file_format)#ZIP64). And it probably also needs to be reworked because in its current form, the library is likely going to run out of memory before the zip would be extracted.

**Comment by jimmywarting** [comment]
> the library is likely going to run out of memory before the zip would be extracted.

There are ways around it. you don't necessarily have to keep everything in memory. Using things such as [stream & pipes](https://streams.spec.whatwg.org/) or [StreamSaver](https://github.com/jimmywarting/StreamSaver.js) to offload the zip parts you have already generated. or read as long as you don't buffer everything up to the memory

I would very much like to get zip64 support to my [streaming zip](https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/zip-stream.js) version but the zip64 format is beyond my knowledge (it has no inflate or deflate option since it's only meant to help saving multiple files to the disk and have a fast pack/unpack)

Any guidens or code example to how to generate a valid zip64 formated file would be much appreciated

(I'm also wondering if crc is even at all necessary when you only need to generate a zip and never have to unpack it)

**Comment by jimmywarting** [comment]
If you are interested, Here is my attempt at writing a streamable zip writer without the need of any web storage or memory allocation. and unlike zip.js you don't have to know what the entry size is
https://jimmywarting.github.io/StreamSaver.js/examples/saving-multiple-files.html, everything is piped to the disk

```js
const files = [
  ['some-folder/cat.mp4', 'https://d8d913s460fub.cloudfront.net/videoserver/cat-test-video-320x240.mp4'],
  ['some-folder/status.txt', 'https://httpbin.org/get'],
  ['some-folder/teapot.txt', 'https://httpbin.org/status/418']
].values() 
// Getting a iterator `.values()` is good for task where you
// have to iterate over values but can't use a for-loop, due to async nature

new ZIP({
  pull (ctrl) {
    const entry = files.next()
    if (entry.done) {
      ctrl.close()
    } else {
      const [name, url] = entry.value

      return fetch(url).then(res => {
        ctrl.enqueue({
          name,
          stream: () => res.body
        })
      })
    }
  }
}).pipeTo(streamSaver.createWriteStream('archive.zip'))
```

My only wish is for it to generate a zip64 file

**Comment by AurelienMendes** [comment]
@jimmywarting Have you an equivalent way to read (not write) a Blob (not physical files) that exceed 4Gb ?
Thanks

**Comment by jimmywarting** [comment]
@AurelienMendes I built have built https://github.com/transcend-io/conflux/ to read & write zip files in a much faster way then jsZip with much less overhead. zip.js is doing a grate (equivalent speed/work) at reading and writing zip's too. only diffrent is conflux operates on whatwg streams that are built into the browser (allowing you to read and write large files) conflux also has support for reading zip64 formats

**Comment by jardicc** [comment]
> > the library is likely going to run out of memory before the zip would be extracted.
> 
> There are ways around it. you don't necessarily have to keep everything in memory. Using things such as [stream & pipes](https://streams.spec.whatwg.org/) or [StreamSaver](https://github.com/jimmywarting/StreamSaver.js) to offload the zip parts you have already generated. or read as long as you don't buffer everything up to the memory

You have to still keep in mind that for 4+GB files it has to be ZIP64 file format otherwise it won't work. https://blog.yaakov.online/zip64-go-big-or-go-home/ And current demo in StreamSaver uses old Zip file format that can't handle 4GB+

**Comment by gildas-lormeau** [comment]
I manually merged the PR https://github.com/gildas-lormeau/zip.js/pull/206 and implemented the code to read a file.
