### ISSUE TITLE
Chrome 62 do not support `BigInt`

### ISSUE THREAD

**Issue by lovelyelfpop** [gildas-lormeau/zip.js#254]

**Comment by gildas-lormeau** [comment]
Well, I confirm Chrome supports `BigInt` since the version 67, cf. https://caniuse.com/bigint

**Comment by gildas-lormeau** [comment]
Here is some additional info. `BigInt` is used for:
- writing/reading files using zip64 (e.g. > 4GB)
- coding/decoding the NTFS extra field. It is used to store the last modified date, the creation date, and the last access date of file entries for NTFS. This code is surrounded by a `try/catch` to ignore errors.

This means that zip.js should work in browsers that don't support `BigInt` as long as zip64 is not involved.

**Comment by lovelyelfpop** [comment]
`10000n` raises syntax error on chrome 62

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. I updated the code in order to use `BigInt(10000)` instead of `10000n`.

**Comment by tophf** [comment]
@gildas-lormeau, the library also uses [flat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) available since Chrome 69 / FF 62 so I wonder do you target these versions explicitly. Either way, it would make sense to configure automatic transpilation via babel+corejs+browserlist that will automatically add the necessary polyfills. Personally I suggest not going below Chrome 55 / FF 52 that implemented async+await because the polyfill for this feature is big and awkward.

**Comment by gildas-lormeau** [comment]
@tophf Thanks for the information, I removed the use of  `Array#flat`.

**Comment by tophf** [comment]
@gildas-lormeau, 5d5b26d35b1da6b7099edde01e2b9196a612140e reads globals from `globalThis` which is supported only since Chrome 71. I guess this is an oversight, which can be fixed by copying the code added by your bundler in dist (`typeof globalThis !== 'undefined' ? globalThis : global || self`). BTW you can probably use a eslint plugin like [eslint-plugin-compat](https://github.com/amilajack/eslint-plugin-compat) in your test suite when building dist, I didn't yet try the plugin myself.

**Comment by gildas-lormeau** [comment]
Thank you @tophf, I applied your suggestion. Honestly, the compatibility is not really important to me. I consider it's a build problem which can be fixed by the developer using the library.

**Comment by tophf** [comment]
I agree. The reason I asked is that a Mozilla's addons reviewer told us to use unaltered vendor libraries as-is in Violentmonkey. Now that I think of it again, they didn't object to our custom build of CodeMirror... so next time such an issue occurs I'll try compiling via our normal workflow.

**Comment by gildas-lormeau** [comment]
I had the same kind of issue with SingleFileZ (which uses zip.js). I fixed it by "forking" the code of third party libraries I use since it's not forbidden.

**Comment by gildas-lormeau** [comment]
@tophf FYI, I just published the version 2.6.30 including the fix you suggested.

**Comment by tophf** [comment]
:-) FYI, now it fails on object destructuring operator `{...foo}` (Chrome 60+, FF 55+) and `async* getEntriesGenerator` (Chrome 63+). I guess we'll babelize it ourselves.

**Comment by gildas-lormeau** [comment]
Thank you for the info @tophf. FYI, I used to provide an ES5 build but the procesing time was very long and I could not test the code anymore on IE11 (this was the purpose of the built files). Maybe this (rollup) script could help you: https://github.com/gildas-lormeau/zip.js/blob/9e65bce1557483154fe576319f4340898a858e93/rollup-es5.config.js.

**Comment by gildas-lormeau** [comment]
I just added https://github.com/gildas-lormeau/zip.js/blob/master/rollup-es5.config.js and https://github.com/gildas-lormeau/zip.js/blob/master/rollup-es5.config.js which allows you to build with rollup and babel zip.js and make it compatible with older engines. See the comment in the file for the instructions.

**Comment by tophf** [comment]
Yeah, it should work, we use the same approach for our main build in Violentmonkey.
