### ISSUE TITLE
Wrong types for FS 

### ISSUE THREAD

**Issue by sebastjon** [gildas-lormeau/zip.js#324]
I wonder if the types for `FS` are correct. 
In your code `FS` and all types  of `ZipEntry` are classes. However, only the interfaces are exported for Typescript.

I would like to call `const fs = new zip.fs.FS()`.

This is a problem because `zip.fs.FS` looks like an instance of the class according to the types, but it is actually the class itself.

I would therefore create a pull request that exports the classes (with constructors) instead of the interfaces.

This would also mean that this line changes from:
`export const fs: { FS: FS, ZipDirectoryEntry: ZipDirectoryEntry, ZipFileEntry: ZipFileEntry };`

to: 
`export const fs: { FS: typeof FS, ZipDirectoryEntry: typeof ZipDirectoryEntry, ZipFileEntry: typeof ZipFileEntry };`

Is this right or am I thinking wrong?

**Comment by gildas-lormeau** [comment]
I think you're right, the autocomplete in VSCode agrees with you. Actually, I don't write TypeScript code and I did not know that classes were instances of interfaces. I don't understand why `typeof` is needed, I guess I need to read the manual.

If you would like to do a PR, I will be happy to merge it, otherwise I can apply the fix for you.

**Comment by mon** [comment]
I also had trouble (even after a manual cast to the FS type) using `.entries` and using some file attributes like `.name`, so I gave up and migrated my code to the ZipReader class 😅 The PR would be appreciated!

**Comment by gildas-lormeau** [comment]
No, the documentation does not really help me. Actually, what is the result of `typeof FS`? The interface of the class?
