### ISSUE TITLE
Expose exportZip on ZipDirectoryEntry

### ISSUE THREAD

**Issue by Wintermoose** [gildas-lormeau/zip.js#381]
Hi,

Would it be possible to expose the exportZip method on ZipDirectoryEntry, in the typescript declaration file? Or is there a reason why this isn't done (like it's not considered stable)? We're using this (excellent!) library for excel file creation, and for that we need to specify the mime type (or create another blob from the output blob), but the otherwise useful wrappers (exportBlob etc) don't expose a way to set it, so we have to go through exportZip( new BlobWriter(mime), ...)

Alternatively, adding the option to specify it directly in the export* helpers would be of course great, but that means changing the api (new parameter, or new entry in options)

**Comment by gildas-lormeau** [comment]
Thank you for the suggestions. I had decided not to expose `exportZip` because I was not sure it would be useful. However, your example shows there's a need especially when using custom `Writer` implementations, where the parameters to pass to the constructor are unknown by zip.js.

In the end, I decided to implement both of your suggestions :)

**Comment by Wintermoose** [comment]
Thank you, that was really unexpectedly fast (before my code with a workaround went through PR...)

Just a small suggestion - you might want to make the mimeType optional.

**Comment by gildas-lormeau** [comment]
Yes... I will fix this :p

**Comment by gildas-lormeau** [comment]
And it's officially released as v2.6.56 :)
